### ISSUE TITLE
can't load scene with with InteractiveSceneChanger

### ISSUE THREAD

**Issue by 13Character5** [func-godot/func_godot_plugin#21]
![Screenshot_20240619_102137](https://github.com/func-godot/func_godot_plugin/assets/75284625/6a4661c7-60b7-4ee6-a61a-2832ff858ba3)
when i try to load a scene utilizing func_godot with InteractiveSceneChanger, it sits at at least 90% forever. is it something on my end?

**Comment by RhapsodyInGeek** [comment]
You haven't provided enough information about exactly what you're doing, but honestly it's very likely something on your end.

FuncGodotMap nodes don't actually perform any of the standard processing callbacks. It only really does work upon calling `build()`, whether through the button or in code. Otherwise, it's basically like any other Node3D. Even the class names have been prefixed to make sure they don't conflict with other plugins or your own project classes, so there really shouldn't be any compatibility issues with other plugins.

**Comment by RhapsodyInGeek** [comment]
Closing this thread as it has not received a response in over a month. I can only assume the issue was either resolved or not important enough to follow up on. Additionally we cannot guarantee compatibility with other plugins (though there really shouldn't be any compatibility issues if they don't touch .map files).
