### ISSUE TITLE
Compatibility Issues with Older TrenchBroom Versions and GameConfig.cfg Export Format

### ISSUE THREAD

**Issue by Pesquisador-Stefano** [func-godot/func_godot_plugin#26]
Hi everyone,

I'm currently working with a PC that has lower specs than most modern calculators. Unfortunately, I can't run the newer versions of TrenchBroom because my system doesn't support the latest OpenGL versions (I can only run Godot in compatibility mode). However, I can still run TrenchBroom versions older than 2021.1.

The problem I'm encountering is that the 'trenchbroom_game_config.gd' script exports the 'GameConfig.cfg' in a newer format, which isn't compatible with these older TrenchBroom versions. While I understand this isn't a common issue for most users, it would be helpful for those of us with older systems if there were an option to export in the older format as well.

I could manually create a GameConfig.cfg file, but this wouldn't improve usability. While I can still create independent maps, having compatibility with older versions would greatly enhance the workflow for anyone in a similar situation.

**Comment by RhapsodyInGeek** [comment]
Unfortunately the Core Team is small, and trying to support older TrenchBroom versions is complex and, as you can imagine, not very high on our priority when most of our users tend to switch to the latest version. One of our core design rules is to only concern ourselves with the latest versions of the tools we want to be compatible with, since it's more than just TrenchBroom we have to pay attention to. We also have a lot of other projects we work on.

That said, FuncGodot is a fully open source project. If you or some other contributor can add backwards compatibility to the appropriate resources via a drop down menu that always defaults to the latest version, I'd be open to guiding that PR (though I'm quite busy and admittedly don't have this issue so I won't be hands on).

TrenchBroom does typically keep pretty good documentation on the GameConfig formats. Older versions of Qodot also have setups for older versions. I'd recommend researching those and the GameConfig files that come included with TrenchBroom 2021 heavily before trying to implement them.

Leaving this issue open for now to allow discussion and potential implementation. Will close if it becomes inactive or resolved.

**Comment by RisingThumb** [comment]
The way this is implemented should consider future GameConfig changes too, and allowing it to be simple for the old gameconfig format to added.

Additionally if this is added, it'd be worthwhile noting somewhere(in the docs?) these gameconfig versions aren't actively supported by the core developers or widely used by people in general. I don't think Trenchbroom goes out of their way to make bug fixes for old versions either

**Comment by RhapsodyInGeek** [comment]
The way TrenchBroom seems to be historically run is "out with the old, in with the new". It makes pretty much zero considerations for backwards compatibility, at least as far as the GameConfigs go. At least, that's as far as my experience has been when fixing and updating the TrenchBroom GameConfig resources for both Qodot and FuncGodot.

**Comment by RhapsodyInGeek** [comment]
Resolved by #27
