### ISSUE TITLE
Can't initialize exported properties from Base custom node types for their derivate types

### ISSUE THREAD

**Issue by azur-wolf** [func-godot/func_godot_plugin#33]
```gdscript
@tool
class_name Base extends Node3D


@export var func_godot_properties

@export var whatever: String = ""

func _func_godot_apply_properties(entity_properties):
	whatever = entity_properties["whatever"] # thats the line that matters here
```

```gdscript
@tool
class_name Derived extends Base

func _ready():
    print(whatever) #should print "Derived_whatever" but instead prints empty string

```
`func_godot_properties` is inherited by `Derived` and it has its respective properties from TB on `FuncGodotFGDEntityClass.class_properties` that correspond to the FGD for `Derived`.

But then for some reason doesn't use either the value from the current instance → `"Derived_whatever"`, or the default one defined on the FGD for `Base` on `FuncGodotFGDEntityClass.class_properties` → `"Base_whatever"`.
All ok.

So `whatever` == `""` still.

That doesn't allow to initialize properties common to a type hierarchy on their base type, so every derived type must explicitly have its own `whatever = entity_properties["whatever"]` for every single property it inherits, forcing repetition.

Being able to would simplify working with type hierarchies and avoid boiler plate.
Not sure if its simple or not to do though.

Srry if the explanation is unclear just tell me

**Comment by RhapsodyInGeek** [comment]
The Example Basic seems to refute this assertion. Marsfrog is a derived class extending from Actor, which extends from CharacterBody3D. You can see how it handles it here:

https://github.com/func-godot/func_godot_example_basic/tree/main/entities/actors

Be sure to check out both the Actor script and the Marsfrog script.

I also use inheritance all over several projects using FuncGodot. 

Do you have a minimum reproducible project you can share?

**Comment by azur-wolf** [comment]
in your Actor-Marsfrog example can't see any use of the _func_godot_apply_properties() to set an exported var declared on the base class, in the derived class instance inherited var

in my code example there's the `@export var whatever`
`Derived` inherits it
was expecting it to be initialized from the `Base` script but applied on the `Derived` instance

do you mean the `super._ready()`?

**Comment by RhapsodyInGeek** [comment]
Actor has exported `flags` and `targetname` variables, which are both shown off in the demo project. Please read the code more carefully - it does exactly the same types of things that you're saying don't work.

I don't mean `super._ready()`. When are you expecting it to `print(whatever)`? After building the map or upon running the scene?

Basically what happens is:
- FuncGodot instantiates nodes
- Nodes run their `_init()`
- FuncGodot adds nodes to scene
- Nodes run their `_ready()`
- FuncGodot loops through each generated node and sets the `func_godot_properties` Dictionary
- FuncGodot loops through each generated node and tries to call `_func_godot_apply_properties()` and make a deferred call to `_func_godot_build_complete()`

So I would not expect `whatever` to print anything because it won't be set until after the `_ready()` function is called.

**Comment by RhapsodyInGeek** [comment]
Closing due to lack of response from OP who has been active in other issues, as this is not an actual bug or plugin issue but rather a user misunderstanding of order of operations. Explanation of op order should be sufficient to consider this issue resolved.
