### ISSUE TITLE
Bug in function apply_entity_occluders

### ISSUE THREAD

**Issue by rantrave-git** [func-godot/func_godot_plugin#35]
**Type**: Bug
**File**: https://github.com/func-godot/func_godot_plugin/blob/main/addons/func_godot/src/map/func_godot_map.gd#L708

## Problem
`indices` both resized and appended, leads to zeros in the middle. `indices.append` should be replaced with item assignment.

**Comment by RhapsodyInGeek** [comment]
Need a bit more of an explanation as to what the actual effect of this bug is, what the effect it has on building is, because so far I haven't experienced any reports of issues with Occluder generation nor experienced any issues myself.

**Comment by rantrave-git** [comment]
`resize` adds empty [0,0,0] polygons. Because they're valid it doesn't visibly change anything, but increases memory consumption, and decreases performance. Assume `resize` has been added to optimize code, but it made exactly opposite.

Valid solutions would be either remove `resize` at all or replace `append` with assigning each already added index with corresponding value.

**Comment by RhapsodyInGeek** [comment]
Ah, I see it now, yeah. Good catch.

I think the more performant thing to do would be to get rid of the append, replace it with a direct assignment, since a single `resize` snags the memory needed in one go. We'll need to keep track of the index offset as we move through the surfaces though, but that isn't really a big deal.
