### ISSUE TITLE
string values on choices without "" throw TB error and choices without description cause func_godot_properties be empty

### ISSUE THREAD

**Issue by azur-wolf** [func-godot/func_godot_plugin#36]
have catch a couple

in `FuncGodotFGDEntityClass.class_properties` a choice with `String` name, value of `Dictionary` and inside the dictionary `Strings` both keys and values. (using exactly the same string)
![image](https://github.com/user-attachments/assets/48e1d3df-810f-47f4-b8ac-782d9fb57a06)

If the `String` value isnt closed by `""` TB will throw an error when trying to open a map.

![image](https://github.com/user-attachments/assets/a0f3e23f-c07a-4166-8f6c-89f719ffe888)

if TB already open it crashes on `F6` to refresh entities

Only happens with `String` values within choices.

`func_godot_properties` stays empty if have any choices without its respective properties description. 

Both things not mentioned in the docs.

**Comment by RisingThumb** [comment]
Have encountered and been thrown off by this issue before in my own work. Took me a while to figure out why.

Note this doesn't happen when you use an int instead of a string for the value of your choice. For consistency with all the other key-value types, I'm personally in favour of addressing this so that that it doesn't need " in the string(However this would likely be a breaking change that breaks peoples setups with choices). iirc I discussed this with Tim so he'll probably have some thoughts on it

Easiest thing to do for now, would be to just document it
