### ISSUE TITLE
Label3D doesn't work for fgd entities on map build.

### ISSUE THREAD

**Issue by azur-wolf** [func-godot/func_godot_plugin#43]
for some reason `Label3D` doesn't work for fgd entities.

![image](https://github.com/user-attachments/assets/21f504ac-1ac9-493e-9561-8e10d8635e83)

No `Label3D` gets instanced, just a plain `Node3D` and the script isn't attached also.

It is a point entity.

**Comment by RhapsodyInGeek** [comment]
It works. You've done something wrong. Please double check that you've created your entities correctly. Also check to make sure you've added your new entity to your FGD File resource.
![image](https://github.com/user-attachments/assets/2a4cdc6d-bc17-446b-8ae4-e0bb50f33c7d)
![image](https://github.com/user-attachments/assets/efcd36d6-f47f-4853-a552-3b13569d0834)

Additionally, the error you're receiving is usually caused by not reloading Godot after creating a new tool script class.

FuncGodot uses ClassDB to generate Nodes by class name via String. As long as the class is a built-in type or added through GDExtension, it will generate whatever node is defined in Node Class. If it cannot find the entity definition (typically caused by either using the incorrect FGD in your Map Settings or by forgetting to add your entity to your FGD File resource), then it will automatically create a Node3D. If there are brushes defined in the entity entry in the map file, it will also generate a MeshInstance3D.
