### ISSUE TITLE
group hierarchy not working

### ISSUE THREAD

**Issue by pantsgt** [func-godot/func_godot_plugin#44]
when i group brushes in trenchbroom and build the map in godot, i get 3d nodes at 0,0,0 on all the groups and the brushes are all in worldspawn

**Comment by RhapsodyInGeek** [comment]
This is by design. Only entities other than `worldspawn` will be separated into Groups and Layers. Multiple Worldspawns will _not_ be created. From the FuncGodot Manual:
> If true, will organize Scene Tree using Trenchbroom Layers and Groups. Layers and Groups will be generated as *Node3Ds*. All structural brushes will be moved out of the Layers and Groups and merged into the Worldspawn entity. Additionally, any Layers toggled to be omitted from export in TrenchBroom will be freed on map build before the Layers' children can apply func_godot_properties or call `_func_godot_apply_properties()` and `_func_godot_build_complete()`.

Be sure to read the manual if something is not working the way you expect it to, as it may be by design:
https://func-godot.github.io/func_godot_docs

**Comment by colinegge** [comment]
I encountered the same issue when migrating from qodot - what is the point of this feature if brush groups are not maintained? Trenchbroom is designed around using groups to organize brushes (instanced groups, etc)
